### ISSUE TITLE
authorship and licensing

### ISSUE THREAD

**Issue by mignon-p** [sparkfun/SparkFunDMX#2]
The `README.md` file says:

> Library written by Andy England (SparkFun) with help from code written by Matt Tong.

And the `LICENSE.md` file says the code is licensed under the MIT license.

However, `SparkFunDMX.h` and `SparkFunDMX.cpp` contain the text:

```
// Copyright (C) 2015  Rick <ricardogg95@gmail.com>
// This work is licensed under a GNU style license.
```

This is a completely different author and license.  I am confused.  (Also, it is not clear what is meant by "GNU style".  Either it's under some specific version of the GPL or LGPL, or it's not.)

**Comment by AndyEngland521** [comment]
Fixed, all should've been licensed MIT originally, sometimes the tops of old files make it through
