### ISSUE TITLE
Starting Data still not working?

### ISSUE THREAD

**Issue by us292231** [sparkfun/SparkFunDMX#5]
Seeing weird behavior.  On a cheap 24 channel light board when I send data on 7 channels I mostly get good data.  However, when I put values on the higher channels I get random junk.

When I connect to a big light board I get all kinds of junk data in the read values.

I don't know for sure, but it looks like the packet start is not working.

How can I diagnose this?

**Comment by luksal** [comment]
You can try https://github.com/luksal/ESP32-DMX-RX which uses the ESP hardware break detection feature and hopefully is more stable. At least with my circuit it works on grandMA2 and a cheap 48 channel light board.
