### ISSUE TITLE
Simultaneous send & receive operation

### ISSUE THREAD

**Issue by m-elias** [sparkfun/SparkFunDMX#6]
I'd like to send and receive DMX data in the same sketch. It looks to me like the library is only intended for one or the other so it definitely will need modification but I think the only issue would be making sure it doesn't receive the same data it transmitted. So just turn off the receiving while sending?

**Comment by AndyEngland521** [comment]
As this library is not intended for this functionality, I am closing this issue. I do believe you're on the right track, although I'd also check out this library https://github.com/claudeheintz/LXESP32DMX
